### ISSUE TITLE
Font / Franklin

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/planlaegger#14]
Er det muligt at få franklin på? 

Der er muligvis nogle font-justeringer ift. vertikal/horisontal alignment men før jeg noterer dem vil jeg gerne lige se det med den rigtige font :)

**Comment by jonaslading** [comment]
Jeg bruger samme typekit id som for til ilog'en (use.typekit.net/ldl1xnu.js), og jeg får den rigtige font i mit lokal miljø. Kan det være et licence issue eller lignende med jeres typekit konto?

**Comment by appeardk** [comment]
Det kan det snildt. Det er sikkert et spørgsmål om at få lukket op for domænet i TypeKit konfigurationen. Hvis blot din kode er opsat som på i-Log så bør det jo løse sig når vi får det op på vores eget domæne lige straks.

**Comment by jonaslading** [comment]
cool, jeg lukker issue's
