### ISSUE TITLE
updatePlannerUrl

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/planlaegger#31]
Sendt på mail d. 16/12

Planlæggeren er nu integreret ind i mit-gyldendal portalen (test miljøet), og det fungerer super godt, du kan evt. prøve at logge ind her:  http://gyldendal.felskov.io/mit-gyldendal/

Mads har skrevet følgende:

Jonas skal helt konkret sørge for, at undersøge om en funktion ved navn window.parent.updatePlannerUrl er tilgængelig. Såfremt den er det, så skal han kalde den når brugeren skifter adresse med den opdaterede hash (f.eks. /planner/5298535cdf1492053058fbbc).
Det gør os i stand til at gribe URL-skifte i Mit Gyldendal og således opdatere parent adressen, således at brugeren vil kunne copy-paste linket og lande på den rigtige planlægger igen.

Jonas skal desuden være opmærksom på, at såfremt window.parent.updatePlannerUrl er tilgængelig, så skal han bruge location.replace ved opdatering af URL'er. Det er for at undgå at "tilbage"-knappen i browseren først trigger et redirect inde i planlægger-iframen og så først anden gang opdaterer URL'en ude i Mit Gyldendal.

Du var meget velkommen til at skrive til Mads på mads@felskov-aps.dk hvis du har spørgsmål :)

**Comment by jonaslading** [comment]
Jeg har prøvet at opfylde det ovenstående, men kan ikke teste hvor vidt jeg har forstået indstrukserne korrekt fra min ende. Så gi endelig lyd hvis det ikke spiller.

**Comment by appeardk** [comment]
Hej, vi har netop forsøgt. 

Det virker umiddelbart ikke. Mads mner at du ikke sender window.location.hash med ved kaldet til updatePlannerUrl :)

Stemmer det?
