### ISSUE TITLE
Listeoversigt - Værktøjsikoner

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/planlaegger#33]
Værktøjsikonerne (skraldespand og blyant) står ikke længere ude til højre.

![screen shot 2015-01-05 at 14 53 05](https://cloud.githubusercontent.com/assets/1305280/5613850/9c00143a-94ea-11e4-88f5-56c2de82c347.png)

**Comment by jonaslading** [comment]
Dette bør bare være en indtastning brugt til udvikling. Hvis du bare sletter den, bør de næste oprettede planlæggere opføre sig rigtigt
