### ISSUE TITLE
Farvekode

### ISSUE THREAD

**Issue by appeardk** [AreWeThereYeti/planlaegger#38]
Jeg vil gerne bede om et estimat på følgende:

Kunden har besluttet at de ALLIGEVEL gerne vil kunne farve-style viser-delen af en planlægger (dvs. ikke listeoversigten).

Vil du estimere følgende:

Farvekoden skal defineres på baggrund af det produkt man vælger fx biologi.gyldendal.dk. Selve hex værdien hardcoder vi bare, så den skal ikke hentes fra API. Hardcodingen må gerne være løst på en måde så det ikke er alt for besværligt at rette en farve for et produkt så det slår igennem på eksisterende planlæggere med samme produkt.

Det er kun den orange farvekode der skal ændres i viseren, de øvrige farver bevares.

Ligesom på den nuværende planlægger skal farven i toppen (af eksport) også følge den definerede farvekode:

![screen shot 2015-01-06 at 18 54 10](https://cloud.githubusercontent.com/assets/1305280/5633221/7d590fbe-95d5-11e4-80fc-943002e92595.png)

**Comment by jonaslading** [comment]
Hvis jeg får leveret en liste med produkter og deres respektive farver, kan jeg ordne det på en time

**Comment by appeardk** [comment]
Hermed farvekoder. Prioriteret lavere end i-log.


FAG / HEX farvekode
	
Billedkunst 1.-2.	#960202
Dansk 0.-2.	#960202
Dansk 3.-6.	#960202
Dansk 7.-10.	#960203
Religion 7.-9.	#3a9b7f
	
Religion 4.-6.	#3a9b7f
Samfundsfag 8.-9.	#317182
	
Tysk 8.-9.	#00B9A5
Biologi 7.-9.	#3f7c31
	
Fysik/Kemi 7.-9.	#114275
	
Matematik 1.-3.	#30669a
Matematik 7.-9.	#30669a
Matematik 4.-6.	#30669a
Natur og teknologi 3.-6.	#30679b
	
Engelsk 5.-7.	#31689e
Engelsk 8.-9.	#31689e
Engelsk 0.-2.	#31689e
Geografi 7.-9.	#326558
